#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.5.{build}-{branch}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/SmartCache.Client/SmartCache.Client.csproj --configuration Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/SmartCache.Client.UnitTests/SmartCache.Client.UnitTests.csproj --configuration Release --no-build
- dotnet test test/SmartCache.Client.IntegrationTests/SmartCache.Client.IntegrationTests.csproj --configuration Release --no-build

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: OPXvDIu5JxGdU/PmLD7IFEkBJ342pugl8CNZDHNYYqqdiZCfaASFJ5LCCpncfqG+
  skip_symbols: false
  artifact: /.*\.nupkg/
